version: '3.8'

services:
  db:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3307"
    networks:
      - app-network

  ecommerce:
    build:
      context: ./ecommerce
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "5000:5000"
    networks:
      - app-network

  store:
    build:
      context: ./store
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "5001:5001"
    networks:
      - app-network

  exchange:
    build:
      context: ./exchange
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "5002:5002"
    networks:
      - app-network

  fidellity:
    build:
      context: ./fidellity
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "5004:5003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
