
services:
  
  ecommerce:
    build:
      context: ./ecommerce
    ports:
      - "5000:5000"
    networks:
      - app-network

  store:
    build:
      context: ./store
    ports:
      - "5001:5001"
    networks:
      - app-network

  exchange:
    build:
      context: ./exchange
    ports:
      - "5002:5002"
    networks:
      - app-network

  fidellity:
    build:
      context: ./fidellity
    ports:
      - "5004:5004"
    networks:
      - app-network

  database:
    build:
      context: ./database
    ports:
      - "5005:5005"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
