FROM python:3.9-slim
# Set the working directory
WORKDIR /exchange
# Copy the application code into the container
COPY Req2.py /exchange
# Install dependencies
RUN pip install flask
RUN pip install requests
RUN pip install mysql-connector-python
# Expose the application port
EXPOSE 5002
# Command to run the application
CMD ["python", "-u", "Req2.py"]