FROM python:3.9-slim
# Set the working directory
WORKDIR /ecommerce
# Copy the application code into the container
COPY Req0.py /ecommerce
# Install dependencies
RUN pip install flask
RUN pip install requests
RUN pip install mysql-connector-python

# Expose the application port
EXPOSE 5000
# Command to run the application
#RUN  sleep 10s
CMD ["python", "Req0.py"]