FROM python:3.9-slim
# Set the working directory
WORKDIR /database
# Copy the application code into the container
COPY database.py /database
# Install dependencies
RUN pip install flask
RUN pip install requests
RUN pip install mysql-connector-python

# Expose the application port
EXPOSE 5005
# Command to run the application
#RUN  sleep 10s
CMD ["python", "-u", "database.py"]